### PR TITLE
New R sensing circuit, PCB update

### LINKED ISSUE #5: Feed 5V and 3V3 converters directly from +12V rail
Rather than cascading them

- [x] Edit SCHM
- [x] Edit PCB

### PR DESCRIPTION
**Pull request by martinroger**
- PNP constant current R sensing circuit added on PCB
- Metadatas aligned
- BOM updated --> Still needs additional details on new components
- Power supply and protection circuit first implementation
- Some rerouting

Resolves #5 #13 #4

### CODE REVIEW

**Comment by martinroger** [comment]
@Alex-XNR any suggestion on the diode type ? Or is there generally a smarter circuit than using the PNPs (which I guess would have variable hFe values)?
I'll also integrate the changes for #17 (Capacitors on PS1 input) in this one. I lifted that design directly from the Arduino Giga schematic so I assumed they had a good reason for capacitors in series.

**Comment by Alex-XNR** [comment]
We could skip to a more robust circuit if you prefer :) Transistors tend to vary a lot with temperature as well, which isn't ideal for a device going onto a hot car dash. I'm happy to take this and propose some options. More accurate/controlled circuits rely on op-amps which can take up some PCB space, but we see what else there is.

Re: #17 , I just looked up the Arduino schematic and it's honestly the first time I've seen that in a released design. I have gone through the datasheet for that part and found a few other bits that need changing. The EN pin resistor divider values don't look good for this application.

**Comment by martinroger** [comment]
> We could skip to a more robust circuit if you prefer :) Transistors tend to vary a lot with temperature as well, which isn't ideal for a device going onto a hot car dash. I'm happy to take this and propose some options. More accurate/controlled circuits rely on op-amps which can take up some PCB space, but we see what else there is.
> 
> Re: #17 , I just looked up the Arduino schematic and it's honestly the first time I've seen that in a released design. I have gone through the datasheet for that part and found a few other bits that need changing. The EN pin resistor divider values don't look good for this application.

Ah, that was my worry about the PNP design. Let me know if there is a schematic or something I could implement. PCB space is not too much of a concern at this stage, we can stretch  it a bit without issues.

Regarding #17 I could technically just try to implement the recommended design from the datasheets, to be fair. Let me know your thoughts.

Also just did the change for

**Comment by martinroger** [comment]
Force-merge after merging from Alex-dev.
Some aspects left hanging

**Pull request merged**
